### ISSUE TITLE
Unclear how to reproduce Alexandria

### ISSUE THREAD

**Issue by DavidKorczynski** [AdaLogics/paper-analyser#12]
The steps to reproduce alexandria is not entirely clear. Could this be added? We are using some grobid_client although it's not clear which module this is (https://github.com/kermitt2/grobid_client_python ?).

Could we perhaps add a script/doc to reproduce?

I think it should be something along the lines of:
```
git clone https://github.com/AdaLogics/paper-analyser
cd paper-analyser/alexandria
python3 -m venv venv
. venv/bin/activate

docker pull lfoppiano/grobid:0.6.2
docker run -t --rm --init lfoppiano/grobid:0.6.2
pip install pymongo bs4 pygrobid
git clone https://github.com/kermitt2/grobid_client_python
python ./runner.py ../example-papers
```
Grobid doc for reference:
https://grobid.readthedocs.io/en/latest/Grobid-docker/

I believe the above steps should be close to enough, but they didn't do it entirely for me. 

@gchers ?

**Comment by gchers** [comment]
My bad, I'll make the pipeline clearer.

Some quick replies:
- which grobid client. I'm waiting on https://github.com/kermitt2/grobid_client_python/pull/26 to be merged; then we can add their grobid_client_python as a submodule. The submodule will have to be fetched & installed after cloning the repo
- FYI: the Grobid docker didn't work for me, for some reason. I've been using `./gradlew run` instead, after building it (https://grobid.readthedocs.io/en/latest/Install-Grobid/). I'll look into that.
- `pip install -r requirements.txt` is the appropriate way (after creating the virtualenv). I think some dependencies are missing from `requirements.txt` atm, though.

**Comment by gchers** [comment]
@DavidKorczynski let me know if this works for you (follow instructions in alexandria/README.md). Close this ticket if it does.

**Comment by DavidKorczynski** [comment]
Got it working now - I had to do a few more things, namely https://github.com/AdaLogics/paper-analyser/commit/400cb2f58a2c12e13a22717ed2f4bb4929350311

**Comment by gchers** [comment]
Sorry for reopening. You shouldn't need to install the grobid python client as a submodule anymore. In fact, I removed the submodule (but something clearly went wrong when I pushed). I opened a PR for this  (#13).

I'll keep this open until we're both sure that the steps fully reproduce.

**Comment by DavidKorczynski** [comment]
Sounds good;
I still needed a few more things from https://github.com/AdaLogics/paper-analyser/commit/400cb2f58a2c12e13a22717ed2f4bb4929350311 in particular the `lxml` library as well as the following the instructions my grobid client ends up being at 8080 rather than 8070 thus also needing the change in `grobid.json`
However, no need for the submodule!

**Comment by gchers** [comment]
Fair enough, good stuff! Thanks, closing now:)
